spring.application.name=bip-web-automation
server.port=8080

# Configuración de archivos
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Rutas para archivos
autumatizaciones.excel.path=V:\\Automatizacion\\BIP\\Selenium\\Recursos
autumatizaciones.output.path=V:\\Automatizacion\\BIP\\Selenium\\Output

# URL del sistema BIP
bip.sucursales.url=http://int.bipsucursales.child01.root.test:5080/
bip.usuario.default=P002331
bip.password.default=Baprosur1
